// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCN9VKiBlYyYRxvkQZhEbEe7igMJdw2lxA',
    appId: '1:558059116503:android:8343a80132400c2c6bdd92',
    messagingSenderId: '558059116503',
    projectId: 'proyectosesamelock',
    storageBucket: 'proyectosesamelock.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAn4H4dq92zncCaIWowSs1qJk8WbUJkfqU',
    appId: '1:558059116503:web:444edda50731347d6bdd92',
    messagingSenderId: '558059116503',
    projectId: 'proyectosesamelock',
    authDomain: 'proyectosesamelock.firebaseapp.com',
    storageBucket: 'proyectosesamelock.firebasestorage.app',
    measurementId: 'G-MX74X5YZB3',
  );
}
